# Generated by Django 3.0.8 on 2021-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('source_acc_no', models.CharField(max_length=122)),
                ('current_balance', models.IntegerField()),
                ('money_deposit', models.IntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
