# Generated by Django 3.0.8 on 2021-04-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='money_deposit',
            new_name='money_transfer',
        ),
    ]
