# Generated by Django 3.0.8 on 2021-04-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210406_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_acc_no',
            field=models.CharField(default=11, max_length=122),
            preserve_default=False,
        ),
    ]
